spring:
  application:
    name: msc
    
  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
    show-sql: true
    
  datasource:
    url: jdbc:mysql://localhost:3306/mscn?serverTimezone=UTC
    username: root
    password: 123456
    
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
